name: 'Spriggit Build'
description: 'Builds an ESP/ESM using Spriggit'
inputs:
  source:
    description:
      'Path to the ESP/ESM source files (the YAML/JSON from Spriggit)'
    required: true
  destination:
    description: 'Path to the ESP/ESM you want to build into with Spriggit'
    required: true
  spriggitVersion:
    description: 'Which Spriggit version to use'
    required: true
runs:
  using: node20
  main: 'dist/index.js'
