name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: yarn install

      - name: Check Format
        id: yarn-format-check
        run: yarn run format:check

      - name: Lint
        id: yarn-lint
        run: yarn run lint

      - name: Test
        id: yarn-ci-test
        run: yarn run ci-test

#  test-action:
#    name: GitHub Actions Test
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        id: checkout
#        uses: actions/checkout@v4
#
#      - name: Test Local Action
#        id: test-action
#        uses: ./
#        with:
#          milliseconds: 2000
#
#      - name: Print Output
#        id: output
#        run: echo "${{ steps.test-action.outputs.time }}"
